---
- name: "[{{ item.name }}] Service deploy"
  block:
    - name: "[{{ item.name }}] deploy"
      community.docker.docker_swarm_service:
        name: "{{ item.name }}"
        image: "rabbitmq:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        env:
          - RABBITMQ_DEFAULT_USER={{ rmq.user }}
          - RABBITMQ_DEFAULT_PASS={{ rmq.password }}
  tags: "{{ name }}"