---
- name: Create network
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: overlay

- name: Services deploy
  include: "../services/{{ item.name }}/service.yml"
  vars:
    - name: "{{ item.name }}"
    - version: "{{ item.version }}"
  loop: "{{ services }}"
