---
- name: Create network
  community.docker.docker_network:
    name: {{ networkName }}
    driver: overlay

- name: Services deploy
  include: "../services/{{ item }}/service.yml"
  vars:
    - name: "{{ item }}"
  loop: "{{ services }}"
