---
- name: Deploy / build server
  hosts: deploy
  roles:
    - role: preconf
      tags: preconf
    - role: build
      tags: build
    - role: deploy
      tags: deploy
    - role: swarm_init
      tags: swarm_init

- name: Manager
  hosts: managers
  roles:
    - role: preconf
      tags: preconf
    - role: swarm_join
      type: manager
      tags: swarm_join


- name: Worker
  hosts: workers
  roles:
    - role: preconf
      tags: preconf
    - role: swarm_join
      type: worker
      tags: swarm_join
  post_tasks:
    - name: Cleang token directory
      file: 
        path:  ./tokens
        state: absent
      ignore_errors: true
      delegate_to: localhost
      tags: swarm_join