Vagrant.configure("2") do |config|
	(1..3).each do |i|
		config.vm.synced_folder '.', '/vagrant', disabled: true # avoid having to run from /mnt/c/
		config.vm.define "server#{i}" do |web|
			web.vm.box = "ubuntu/focal64"
			web.vm.network "forwarded_port", id: "ssh", host: 2222 + i, guest: 22
			if i == 1
				web.vm.network "forwarded_port", guest: 80, host: 80
			end
			web.vm.network "private_network", ip: "10.11.10.#{i}", virtualbox__intnet: true
			web.vm.hostname = "server#{i}"

			web.vm.provision "shell" do |s|
				ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
				s.inline = <<-SHELL
				echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
				echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
				SHELL
			end

			web.vm.provider "virtualbox" do |v|
				v.name = "server#{i}"
				v.memory = 2048
				v.cpus = 1
				v.customize ["modifyvm", :id, "--uartmode1", "disconnected"] # avoid VBoxManage.exe crit error (COM_part ini fail)
				v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"] # DNS host resolver for NAT
			end
		end
	end
end
 
