galaxy_info:
  role_name: deploy
  description: deploy microservice on docker cluster
  author: Veremiychuk Ivan (A. Larichev stepik course)
  license: MIT
  min_ansible_version: 2.12.1
  platforms:
    - name: Ubuntu
      versions:
        - All