---
- name: "[{{ item.name }}] Configure secret"
  include_tasks: "../secret.yml"
  
- name: "[{{ item.name }}] Service deploy"
  block:
    - name: "[{{ item.name }}] deploy"
      community.docker.docker_swarm_service:
        name: "{{ item.name }}"
        image: "{{ registry_name }}{{ name }}:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        secrets:
          - secret_name: "{{ name }}.env.j2"
            filename: "/opt/app/.env"
  tags: "{{ name }}"