---
- name: Initating swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

- name: Save tokens
  set_fact:
    token_manager: "{{ token.swarm_facts.JoinTokens.Manager }}"
    token_worker: "{{ token.swarm_facts.JoinTokens.Worker }}"
    cacheable: yes


# - name: save manager token
#   copy:
#     dest: ./tokens/token-manager
#     content: "{{ token.swarm_facts.JoinTokens.Manager }}"
#     mode: '0777'
#   delegate_to: localhost

# - name: save worker token
#   copy:
#     dest: ./tokens/token-worker
#     content: "{{ token.swarm_facts.JoinTokens.Worker }}"
#     mode: '0777'
#   delegate_to: localhost