---
- name: Initating swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

- name: check directory
  file:
    path: ./tokens
    state: directory
    mode: '0777'
  delegate_to: localhost

- name: save manager token
  copy:
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"
    mode: '0777'
  delegate_to: localhost

- name: save worker token
  copy:
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"
    mode: '0777'
  delegate_to: localhost