---
- name: "[{{ item.name }}] Service deploy"
  block:
    - name: "[{{ item.name }}] deploy"
      community.docker.docker_swarm_service:
        name: "{{ item.name }}"
        image: "{{ registry_name }}{{ name }}:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3001
            target_port: 80
  tags: "{{ name }}"